const data = [
    {
        id:1,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:2,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:3,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:4,
        answers:[
            {dots:"dot",correct:false},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:5,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:6,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:7,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:8,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:9,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:10,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:false}
        ]
    },
    {
        id:11,
        answers:[
            {dots:"dot",correct:true},
            {dots:"dot",correct:false},
            {dots:"dot",correct:false},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true}
        ]
    },
    {
        id:12,
        answers:[
            {dots:"dot",correct:false},
            {dots:"dot",correct:false},
            {dots:"dot",correct:false},
            {dots:"dot",correct:false},
            {dots:"dot",correct:true}
        ]
    }
    

].reverse()